<?php
/**
 * @file
 * Code for the custom CWCON functionality
 */

/*
 * Implements hook_username_alter().
 */
function cwcon_custom_username_alter(&$name, $account) {
  $account = user_load($account->uid);
  if (isset($account->field_first_name[LANGUAGE_NONE][0]['value']) &&
    $account->field_last_name[LANGUAGE_NONE][0]['value']) {
    $name = $account->field_first_name[LANGUAGE_NONE][0]['value'] . ' ' . $account->field_last_name[LANGUAGE_NONE][0]['value'];
  }
}

/**
 * Implements hook_preprocess_node().
 */
function cwcon_custom_preprocess_node(&$vars) {

  // Hide the link to add session materials to a session to anyone who is not a presenter
  if ($vars['type'] == 'session' && !empty($vars['field_all_presenters']) && !user_access('administer nodes')) {
    global $user;
    $presenter_is_viewing = FALSE;
    foreach ($vars['node']->field_all_presenters[LANGUAGE_NONE] as $presenter) {
      if ( $user->uid == $presenter['uid']) {
        $presenter_is_viewing = TRUE;
        break;
      }
    }

    if (!$presenter_is_viewing) {
      unset($vars['content']['links']['nodereference_url']['#links']['presentation_materials_field_related_session']);
    }
  }
}

/**
 * Implements hook_preprocess_page().
 */
function cwcon_custom_preprocess_page(&$vars) {

  // If it's not a session page with an eva twitter view, move on
  if (!isset($vars['node']) || $vars['node']->type != 'session' || !isset($vars['page']['content']['system_main']['nodes'])) {
    return;
  }
  // Move attached eva twitter view to sidebar
  $node_key = element_children($vars['page']['content']['system_main']['nodes']);
  $nid = current($node_key);

  // If there's no EVA twitter view, let's not go through the trouble of switching
  if (!isset($vars['page']['content']['system_main']['nodes'][$nid]['twitter_attach_entity_view_1'])) {
    return;
  }

  $twitter_eva_view = $vars['page']['content']['system_main']['nodes'][$nid]['twitter_attach_entity_view_1'];

  if (isset($vars['page']['sidebar_first']['community_tags_0'])) {
    $twitter_eva_view['#weight'] =  $vars['page']['sidebar_first']['community_tags_0']['#weight'] + .02;
  }
  else {
    // Possible alternative would be to prepend it to array and not invoke re-sort
    $twitter_eva_view['#weight'] = 0;
  }

  $vars['page']['sidebar_first'][] = $twitter_eva_view;
  // Invoke a re-sorting after adding an element
  $vars['page']['sidebar_first']['#sorted'] = FALSE;

  unset($vars['page']['content']['system_main']['nodes'][$nid]['twitter_attach_entity_view_1']);
}
